# Created by trellis-cli v0.7.1
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  newdealseals.com:
    site_hosts:
    - canonical: newdealseals.com
      redirects:
      - www.newdealseals.com
    local_path: ../site
    branch: master
    repo: git@github.com:example/example.com.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
